collections:
  authors:
    output: true
  destinations:
    output: true
  states:
    output: true
  memories:
    output: true
  journals:
    output: true
    permalink: /journal/:title/
  recipes:
    output: true
    permalink: /recipe/:title/

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "destinations"
    values:
      layout: "destination"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "journals"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
  - scope:
      path: ""
    values:
      layout: "default"

destination:
  ../dist

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
